language: node_js
node_js:
    - 7
    - 6
services:
  - postgresql
before_script:
  - psql -c "CREATE USER test;" -U postgres
  - psql -c 'create database node_api_test;' -U postgres
script:
    - npm run test:travis
